version: '3.8'

services:
  frontend:
    build:
      context: './client'
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/code
      - /client/node_modules
    command: npm run start
    ports:
      - 3000
  backend:
    build:
      context: './server'
      dockerfile: ./Dockerfile
    depends_on: 
      - mongo
    volumes:
      - ./server:/code
      - /server/node_modules
    command: npm run dev
    ports:
      - 8833
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
  proxy:
    image: tivix/docker-nginx:v9
    environment:
      - UPSTREAMS=/:frontend:3000,/api:backend:8833
    depends_on:
      - backend
    ports:
      - '8088:80'